# Generated by Django 3.2.13 on 2022-12-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='like_users',
            new_name='like_user',
        ),
    ]
