# Generated by Django 3.2.13 on 2022-11-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_review_book_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book_review',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
