# Generated by Django 3.2.13 on 2022-11-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20221130_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
