# Generated by Django 3.2.13 on 2022-11-30 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_book_review_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_review',
            old_name='like_review',
            new_name='like_user',
        ),
        migrations.AddField(
            model_name='book',
            name='like_user',
            field=models.ManyToManyField(related_name='like_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book_review',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_review_comment',
            name='review',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='books.book_review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_review_comment',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
