# Generated by Django 3.2.13 on 2022-12-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20221130_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_review_comment',
            old_name='review',
            new_name='book_review',
        ),
        migrations.AlterField(
            model_name='book_review_comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
