# Generated by Django 3.2.13 on 2022-12-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_review_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_review_comment',
            name='book_review',
        ),
        migrations.RemoveField(
            model_name='book_review_comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book_Review',
        ),
        migrations.DeleteModel(
            name='Book_Review_Comment',
        ),
    ]
