# Generated by Django 3.2.13 on 2022-12-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
