# Generated by Django 3.2.13 on 2022-12-06 06:45

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='book_review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_review',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
