# Generated by Django 3.2.13 on 2022-12-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_review',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
