# Generated by Django 3.2.13 on 2022-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review_comment',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
