# Generated by Django 3.2.13 on 2022-12-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221206_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
