# Generated by Django 3.2.13 on 2022-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_book_review_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review',
            name='content',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
