# Generated by Django 3.2.13 on 2022-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_book_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
