# Generated by Django 3.2.13 on 2022-12-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221206_1545'),
        ('reviews', '0005_alter_book_review_content'),
    ]

    operations = [
    ]
