# Generated by Django 3.2.13 on 2022-12-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_merge_20221207_0918'),
        ('reviews', '0006_merge_20221207_0924'),
    ]

    operations = [
    ]
