# Generated by Django 3.2.13 on 2022-12-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_date',
            field=models.DateTimeField(),
        ),
    ]
