# Generated by Django 3.2.13 on 2022-12-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='X',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='Y',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
