# Generated by Django 3.2.13 on 2022-12-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='detail_place',
        ),
        migrations.AlterField(
            model_name='group',
            name='introduce',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
