# Generated by Django 3.2.13 on 2022-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20221205_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='X',
        ),
        migrations.RemoveField(
            model_name='group',
            name='Y',
        ),
        migrations.AddField(
            model_name='group',
            name='detail_place',
            field=models.CharField(default='우리집아님', max_length=200),
            preserve_default=False,
        ),
    ]
