# Generated by Django 3.2.13 on 2022-12-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_detail_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='introduce',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='place',
            field=models.CharField(max_length=200),
        ),
    ]
