# Generated by Django 3.2.13 on 2022-12-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20221207_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
